# Generated by Django 5.1.3 on 2024-11-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('weight', models.FloatField(default=0, verbose_name='Weght')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('target_weight', models.IntegerField(verbose_name='Weight_Goal')),
                ('goal', models.CharField(choices=[('1', 'Fat loss'), ('2', 'Muscle gain'), ('3', 'Weight Maintenance')], max_length=1)),
                ('activity_level', models.CharField(choices=[('1', 'Sedentary'), ('2', 'Lightly'), ('3', 'Moderately'), ('4', 'Very active'), ('5', 'Athlete')], max_length=1)),
                ('diet_type', models.CharField(choices=[('1', 'Recommend'), ('2', 'High Protein'), ('3', 'Low-Carb')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
